[package]
name = "musixmatch"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib/mod.rs"

[features]
marcos = ["dep:default-args"]

[dependencies]
api-request-utils-rs = { version = "0.1.7", features = ["export"] }
default-args = { version = "1.0.0" , optional = true }
strum = { version = "0.25", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["full"] }