[package]
name = "musixmatch"
version = "0.1.0"
edition = "2021"

[dependencies]
api-request-utils-rs = { version = "0.1.6-fix1", features = ["export"] }
default-args = "1.0.0"

[lib]
path = "src/lib/mod.rs"
